In [ ]:
# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.



In [3]:
#### 1. Import the numpy package under the name `np` (★☆☆)
#`hint: import … as`
import numpy as np

In [117]:
#### 2. Create a null vector of size 10 (★☆☆)
#`hint: np.zeros`
v1= np.zeros(10)
v1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#`hint: array[4]`
v2 = np.zeros(10)
v2[4]= 1
print(v2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [59]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
#`hint: arange`
v3=np.arange(10, 50)
v3


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [63]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#`hint: reshape`
m=np.arange(0, 9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#`hint: np.nonzero`
A = [1,2,0,0,4,0]
nonzeroind = np.nonzero(A) # the return is a little funny so I use the [0]
print (nonzeroind)
#(array([0, 1, 4]),)


(array([0, 1, 4]),)


In [120]:
nonzeroind2 = np.nonzero(A) [0]
print (nonzeroind2)
#[0 1 4]

[0 1 4]


In [71]:
#### 7. Create a 3x3 identity matrix (★☆☆)
#`hint: np.eye`
idmatr=np.identity(3)
print('3x3 matrix:')
print(idmatr)

#or
idmatr2= np.eye(3)
#print(idmatr2)


3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [75]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
#`hint: np.random.random`
r=np.random.random((3,3,3))
print(r)

[[[0.750717   0.57406383 0.75164399]
  [0.07914896 0.85938908 0.82150411]
  [0.90987166 0.1286312  0.08178009]]

 [[0.13841557 0.39937871 0.42430686]
  [0.56221838 0.12224355 0.2013995 ]
  [0.81164435 0.46798757 0.80793821]]

 [[0.00742638 0.55159273 0.93193215]
  [0.58217546 0.20609573 0.71775756]
  [0.37898585 0.66838395 0.02931972]]]


In [81]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#`hint: min, max`
r2=np.random.random((10,10))
print(r2)
r2min, r2max = r2.min(), r2.max()
print("Minimum and Maximum Values:")
print(r2min, r2max)

[[0.39131649 0.6563432  0.64738515 0.32696819 0.17939017 0.46680988
  0.26328104 0.35506513 0.95414397 0.46113787]
 [0.68489147 0.33622989 0.99586108 0.65876761 0.19600947 0.098184
  0.94318057 0.94477783 0.62132838 0.0169915 ]
 [0.22553488 0.80127678 0.87545983 0.45398981 0.36552062 0.27422501
  0.11697051 0.11574454 0.9526027  0.80862611]
 [0.16477936 0.20705005 0.65555155 0.76466422 0.81031485 0.16333769
  0.98412829 0.22780207 0.58941543 0.58761576]
 [0.96736189 0.65766744 0.58490427 0.51877258 0.76465754 0.10605526
  0.0020919  0.95248887 0.49865768 0.32833538]
 [0.36805326 0.80384332 0.38237021 0.77016917 0.440462   0.84407746
  0.07620406 0.48112833 0.46684971 0.26432798]
 [0.94361474 0.90502846 0.4435963  0.09715961 0.20678315 0.27149184
  0.48421977 0.33837711 0.77413607 0.47602661]
 [0.8703705  0.99578175 0.21983595 0.61167138 0.84750231 0.94523663
  0.29008643 0.72704274 0.01501615 0.87914244]
 [0.06393855 0.7333954  0.99461039 0.50118978 0.20933399 0.59464358
  0.62414998 0

In [83]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
#`hint: mean`
r3=np.random.random((6,5))#np.random.random(30)
print(r3)
r3mean = r3.mean()
print("Mean value:")
print(r3mean)



[[0.7543916  0.11350908 0.77536476 0.58590197 0.83538869]
 [0.43087565 0.62496445 0.55441213 0.97567127 0.75547439]
 [0.54481325 0.17403209 0.90411422 0.20583778 0.65004326]
 [0.93647185 0.22357963 0.22592354 0.85181891 0.82765503]
 [0.35170335 0.26509629 0.12738847 0.9879361  0.8353431 ]
 [0.8993916  0.51367933 0.11438483 0.05258034 0.3305821 ]]
Mean value:
0.5476109693872921


In [116]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#`hint: np.diag`
m2 = np.diag([1, 2, 3, 4],-1)
print(m2)

#m3 = np.diag(1+np.arange(4),-1)
#print (m3)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [123]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#`hint: (x -mean)/std`

n = np.random.random((5,5))
nmax, nmin = n.max(), n.min()
N= (n-nmin)/(nmax-nmin)
print (N)


#mean=np.mean(n)
#std=np.std(n)
#N2 = (n- mean)/std
N2 = (n- np.mean(n))/np.std(n)
print (N2)





[[0.68836226 1.         0.71696908 0.84386912 0.02660461]
 [0.68706014 0.66817656 0.08627412 0.86561576 0.62547591]
 [0.08267756 0.60474098 0.48262577 0.2246953  0.        ]
 [0.36388061 0.63145131 0.32569632 0.30252101 0.76958064]
 [0.77747611 0.73553459 0.08568055 0.52234841 0.56615651]]


In [23]:
#### 13. How to find common values between two arrays? (★☆☆)
#`hint: np.intersect1d`
#help(np.intersect1d)
x = np.array([1, 1, 2, 3, 4])
y = np.array([2, 1, 4, 6])
comv = np.intersect1d(x, y)
comv

array([1, 2, 4])

In [24]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
#`hint: sort`
r4 = np.random.random(10)
r4.sort()
print(r4)



[0.01112412 0.0481593  0.35545295 0.49135545 0.51311402 0.54323964
 0.5774658  0.60664783 0.76648697 0.94752272]


In [128]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#`hint: argmax`
r5 = np.random.random(10)
r5[r5.argmax()] = 0
print(r5)


[0.33909923 0.         0.45882108 0.01484058 0.16322003 0.73992272
 0.73829374 0.75452291 0.35166938 0.35227695]


In [10]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#`hint: mean(axis=,keepdims=)`
import numpy as np
r7= np.random.random((3,4))#1,10
r7b = r7-r7.mean(axis=1, keepdims=True)#axis chooses either to apply either rowwise or columwise
print(r7b)

[[ 0.25307747 -0.27598774 -0.24252682  0.26543709]
 [ 0.14701581 -0.05028003 -0.36976355  0.27302777]
 [ 0.23995049 -0.23248778  0.06406144 -0.07152415]]


In [137]:
#### 17. How to get the n largest values of an array (★★★)
#`Z = np.arange(10000)
#np.random.shuffle(Z)
#n = 5
#hint: np.argsort | np.argpartition`

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])#[9995 9996 9997 9998 9999]Gives you indices

print (Z[np.argpartition(-Z,n)[:n]])#[9999 9998 9997 9996 9995]




[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


In [12]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#`hint: np.where`
r6 = np.random.random((5,3))
np.where(r6 >4, r6, r6**2)
print(r6)

help(np.where)
            
          
            

[[0.72021361 0.85993963 0.44376553]
 [0.76809802 0.80064265 0.49620475]
 [0.35376597 0.0081045  0.59014229]
 [0.95554077 0.61916836 0.21692697]
 [0.39314524 0.25956102 0.93846059]]
Help on function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with e

In [8]:
nums = np.random.randint(0,4,(6,3))
nums

array([[1, 1, 3],
       [1, 2, 3],
       [0, 3, 1],
       [1, 3, 0],
       [1, 0, 3],
       [3, 3, 3]])